# Generated by Django 3.1.7 on 2021-05-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_numb', models.IntegerField(verbose_name='İşlem Numarası')),
                ('islem', models.CharField(max_length=150, verbose_name='İşlem Adı')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': '1 - Muhasebe - İnsan Kaynakları Takip Listesi',
            },
        ),
        migrations.CreateModel(
            name='Checklist2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_numb', models.IntegerField(verbose_name='İşlem Numarası')),
                ('islem', models.CharField(max_length=150, verbose_name='İşlem Adı')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': '2 - Bilgi İşlem Takip Listesi',
            },
        ),
        migrations.CreateModel(
            name='Checklist3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_numb', models.IntegerField(verbose_name='İşlem Numarası')),
                ('islem', models.CharField(max_length=150, verbose_name='İşlem Adı')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': '3 - Oryantasyon Süreci Takip Listesi',
            },
        ),
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontrol', models.CharField(choices=[('Tamamlandı', 'Tamamlandı'), ('Tamamlanmadı', 'Tamamlanmadı')], default='Tamamlanmadı', max_length=100, verbose_name='Kontrol')),
            ],
            options={
                'verbose_name': 'Kullanıcı Kontrol',
                'verbose_name_plural': 'A - Kullanıcı Kontrol (Muhasebe - İnsan Kaynakları Takip Listesi)',
            },
        ),
        migrations.CreateModel(
            name='UserDocuments2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontrol', models.CharField(choices=[('Tamamlandı', 'Tamamlandı'), ('Tamamlanmadı', 'Tamamlanmadı')], default='Tamamlanmadı', max_length=100, verbose_name='Kontrol')),
            ],
            options={
                'verbose_name': 'Kullanıcı Kontrol',
                'verbose_name_plural': 'B - Kullanıcı Kontrol (Bilgi İşlem Takip Listesi)',
            },
        ),
        migrations.CreateModel(
            name='UserDocuments3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontrol', models.CharField(choices=[('Tamamlandı', 'Tamamlandı'), ('Tamamlanmadı', 'Tamamlanmadı')], default='Tamamlanmadı', max_length=100, verbose_name='Kontrol')),
                ('documentNumber', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.checklist3', verbose_name='İşlem')),
            ],
            options={
                'verbose_name': 'Kullanıcı Kontrol',
                'verbose_name_plural': 'C - Kullanıcı Kontrol (Oryantasyon Süreci Takip Listesi)',
            },
        ),
    ]
